### ISSUE TITLE
arp sync issues

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#104]
<@683368206341373954>,<#978315928800485416>,I noticed a patch starting the arp sequence, then after first beat of a 4/4 120bpm sequence, restarting the sequence so the first round of a loop is out if sync. Then the second and all subsequent playthroughs that doesnt happen anymore, arp is fine.

Now this does not happen with same patch and same midi loop note send to real hw Virus B.,[Jump To](https://discordapp.com/channels/829099347975208970/978315928800485416/988363711012012042)

**Comment by jaffasplaffa** [comment]
Not sure if this might be related to this bug, but it does sound kind of familiar:

When Logic Pro is stopped all the arpeggiator patches works fine.

But if I start Logic Pro, all the patches with arpeggiators in, plays only a part of the arpeggio and then stops playing. If even playing at all.

Best wishes,
Jakob

**Comment by ovnis82** [comment]
Same issue with Reaper. The bug is still here...
