### ISSUE TITLE
Linux-VST3 can't load in carla host

### ISSUE THREAD

**Issue by mvdev0** [dsp56300/gearmulator#111]
Hi,

what a amazing Project, thank you so much!

I can test the linux vst2 plugin in carla on a arch linux installation, but not vst3 offered from your side.

The output while loading is "Failed to load file : Could not find the VST2 main entry in the plugin library".

Is there something I'm doing wrong?

Thanks!

**Comment by dsp56300** [comment]
That sounds like a setup issue as a VST3 doesn't contain any VST2 entry point, which Carla seems to complain about.  Does (your version of) Carla support VST3 at all?

**Comment by mvdev0** [comment]
Hello, thank you much for responding.

Yes, I can load other VST3, at time I'm doing this with yabridge without carla-bridge-* .

Today I start reading this is really the prefered way, I do not know it is correct right now.

But *most* Windows-VST2/3 PlugIns are working, some do not show the native GUI (this is why I start rethink about
my setup)
