### ISSUE TITLE
As long as you leave the GUI visible and then open a new instance it doesn't crash. But as soon as you close the GUIs and then load another plugin the DAW crashes

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#119]
<@737017401761071225>,<#841809045505703956>,And I just found out that as long as you leave the GUI visible and then open a new instance it doesn't crash. But as soon as you close the GUIs and then load another plugin the DAW crashes.,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1019267978547695697)

**Comment by mkruselj** [comment]
Cannot confirm with latest builds of all emulated synths.
