### ISSUE TITLE
reverb bpm predelay selection not working 

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#138]
<@826428807597522984>,<#841809045505703956>,Hi guys thx for you work. 1.2.22 have bug in reverb section. 
1.  bpm predelay selection not working  
2. At galaxpel skin predelay knob not working and make same function as decay       
also about knob values at display section. for example if i touch filter or other knob and change value all ok and then if i will change value by mousewheel also all ok.  But if i will not touch for example resonance  knob and start change value by mousewheel at display section it have not any effect, i am need touch it and value start change.
 Also about display section at lfo page ,link knobs osc pitch and filter have not displayed name. 
And yet filter link knob have effect only to env vel parameter. 
Thx,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1051584015171338240)

**Comment by mkruselj** [comment]
1. Cannot confirm with latest OsTIrus
2. Skin probably needs fixing, contact Galaxpel about it.
