### ISSUE TITLE
Windows 11, Cubase 12, if you mix the reverb 100% if feedbacks forever even if you turn it off

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#139]
<@465564675182952469>,<#841809045505703956>,Bug: Latest version, Windows 11, Cubase 12, if you mix the reverb 100% if feedbacks forever even if you turn it off.,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1051617545762906193)

**Comment by mkruselj** [comment]
Not a bug, this is expected because it runs as a send effect.
