### ISSUE TITLE
random cpu spikes about every minute or two

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#144]
<@1007369959715909653>,<#841809045505703956>,I've got some random cpu spikes about every minute or two. Didn't had this in 1.20. Bitwig Studio, Apple M1 Pro chip.,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1052600939518894101)

**Comment by dylanmc** [comment]
I'm also seeing CPU spikes, also have an M1 CPU, also using BitWig Studio. My spikes are more frequent than every minute or two - and result in audible crackling.

**Comment by dylanmc** [comment]
I confirm that today's Vavra beta release (1.3.16, July 13, 2024) does appear to fix the problem on my system. It would be interesting and maybe helpful to the community to describe how it got fixed. Also looking forward to the fix being applied to Osirus and OsTIrus. Thanks!
