### ISSUE TITLE
VCA stops working after some time

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#150]
<@605139074503933961>,<#841809045505703956>,[BUG] latest VST3 Osirus, Virus C 6.5 352 ROM, Win11, Cubase 12 - Virus init patch - VCA envelopes stop working after some time, all sounds like a raw sample, no attack or release is audible no matter  how I set them. Workaround: reloading the plugin solves the issue until the next occurance.,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1072450675365130301)

**Comment by mkruselj** [comment]
I don't think I can confirm this issue... been using the emulator for quite some time and this never showed up.
