### ISSUE TITLE
Fault in single patch midifile save 

### ISSUE THREAD

**Issue by Guod3** [dsp56300/gearmulator#163]
There are 3 bytes that come after the sysex message F7 at the end a of a *.mid single patch save that serve no purpose and cause python midifile functions to crash. Removing these 3 bytes does not effect single patch loading from the *.mid in osirus.

**Comment by ylmrx** [comment]
it works just fine here (i do see those 3 bytes), can you give more context regarding what you attempted ? I couldn't make it crash.
(here: win11, python 3.9.13 / midifile 0.2.0)

**Comment by Guod3** [comment]
I tried various python midi libraries including mido, they raised various errors which went away when I binary edited out the extraneous bytes. Sorry I don't have the specifics anymore, I went on to use my own binary file operations.

**Comment by dsp56300** [comment]
The three bytes FF 2F 00 mark the end of a track, see midi file specification here:
https://www.music.mcgill.ca/~ich/classes/mumt306/StandardMIDIfileformat.html

**Comment by dsp56300** [comment]
Found the issue, the chunk length that was written was incorrect.
