### ISSUE TITLE
State not recalled if project saved while plugin is muted (Reaper Win10 VST2)

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#165]
<@930159337043800156>,<#841809045505703956>,After finding many projects with DSP instances randomly reverted to default preset AutobendBC ,finally  got a solution. The projects were saved with the track containing DSPemu  muted or FX disabled. When I re-open the project and un-mute track or enable FX for the track, The DSPemu instance(s) on that track goes to default preset. Reaperwin10 VST2. Bug or daw?,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1096485438371405944)

**Comment by mkruselj** [comment]
Cannot confirm with latest Osirus+Reaper.
