### ISSUE TITLE
INPUT patch breaking amp envelope

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#174]
<@357655607450402816>,<#841809045505703956>,**Bug: Selecting `Bank A | >>Input<<` patch causes amp envelopes to stop working properly**

Repro steps:
* From a fresh instance, select `Bank A | >>Input<<`
* Immediately load an init patch (i.e. `Bank A | - Init -`)
* Increase the attack and/or release times for the amp envelope
* Observe that only the time portion of the envelope works (i.e. sound starts and ends abruptly, with no fade in or out)

(I'm sure it's something specific to the patch that's causing this, but so far I haven't been able to repro it any other way),[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/1168697821592031263)

**Comment by mkruselj** [comment]
Cannot confirm with latest Osirus.
