### ISSUE TITLE
Parameter State is not getting saved in single mode

### ISSUE THREAD

**Issue by lol-catz** [dsp56300/gearmulator#20]
The parameter state is not getting saved in single mode.   It appears to work in multi mode, however in single mode this functionality is broken..

Reproduce:
Open new project, load plugin, switch to single mode, load init patch, tweak patch, close and save project.
Open project, init patch comes up, but tweaks are lost.

**Comment by dsp56300** [comment]
sorry, I fixed it but forgot that there is a github ticket.
