### ISSUE TITLE
LINUX REAPER freeze/crashes when changing presets .clap

### ISSUE THREAD

**Issue by CodesoundR** [dsp56300/gearmulator#200]
Linux Mint 21.3 Cinnamom_x64 - Reaper 7.15 - DSP56300Emu-1.3.14-Linux_x86_64-Osirus-CLAP.deb

Hi,
I inform you that Reaper crashes when I change presets from the Presets menu. You can't change presets directly from the voice in single mode but only from the arrows with which you only go forward to backward. The pop-up menu that appeared in previous versions does not appear.

codesound@codesound:~/opt/REAPER$ '/home/codesound/opt/REAPER/reaper' 
jack: created client
jack: setting TIME_CRITICAL = 81
LC_NUMERIC / LANG is set to 'it_IT.UTF-8', overriding LC_NUMERIC environment to POSIX
jack: activated client
Program BootROM size = 0x57
Program BootROM offset = 0x100
Program CommandStream size = 0xaf0b
MemoryBuffer@190: MMU based DSP memory setup successful
Jit@121: No profiler detected
write@538: Periph write @ ffffff: 0x000000
write@538: Periph write @ fffffe: 0x000000
write@538: Periph write @ fffffb: 0x012421
write@538: Periph write @ ffffff: 0x000e07
write@538: Periph write @ fffff9: 0x020739
write@538: Periph write @ fffff8: 0x030839
writeTLR@111: Write Timer 0 TLR: ffdff8
writePortControlRegister@86: Write HDI08 HPCR 001c1e
writePortControlRegister@86: Write HDI08 HPCR 001c5e
write@538: Periph write @ ffffa6: 0x003c30
write@538: Periph write @ ffffaf: 0x00000c
updateCyclesPerSample@143: Clock speed changed to: 108 Mhz, EXTAL=12000000 Hz, PCTL=b4006b, mf=00006c, pd=00000c, df=000001 => cycles per sample=1152, predefined samplerate=0
write@538: Periph write @ fffffb: 0x012421
write@538: Periph write @ ffffff: 0x000e07
write@538: Periph write @ fffff9: 0x020739
write@538: Periph write @ fffff8: 0x030839
write@538: Periph write @ fffff7: 0x000001
write@538: Periph write @ fffff6: 0x000001
write@538: Periph write @ ffffff: 0x555000
write@538: Periph write @ fffffe: 0x00035b
writeTransmitClockControlRegister@125: Write ESAI TCCR 400307
writeTransmitControlRegister@111: Write ESAI TCR d07d00
writeReceiveClockControlRegister@139: Write ESAI RCCR 000307
writeReceiveControlRegister@102: Write ESAI RCR 007d00
writeControlRegister@314: Write ESAI CR 000000
writeTransmitControlRegister@111: Write ESAI TCR d07d01
writeReceiveControlRegister@102: Write ESAI RCR 007d01
write@538: Periph write @ ffffd6: 0x000003
writeTLR@111: Write Timer 0 TLR: ffdff8
writePortControlRegister@86: Write HDI08 HPCR 001c1e
writePortControlRegister@86: Write HDI08 HPCR 001c5e
write@538: Periph write @ ffffd6: 0x000003
writeTLR@111: Write Timer 0 TLR: ffdff8
writeTLR@111: Write Timer 1 TLR: ffdff8
writeTLR@111: Write Timer 2 TLR: ffdff8
write@538: Periph write @ ffff90: 0x000183
write@538: Periph write @ ffff90: 0x000183
writeTransmitControlRegister@111: Write ESAI TCR d07d01
writeTransmitControlRegister@111: Write ESAI TCR 507d01
append@84: DSP boot completed
sendInitControlCommands@115: Sending Init Control Commands
writeSingle@950: Loading Single Taurus  JS to part 64
sendPreset@325: Send to DSP: Single to program 64
operator()@168: Resampler input latency 28 samples
operator()@168: Resampler input latency 55 samples
setExtraLatencySamples@46: Latency set to 1000 samples at 46875 Hz
append@42: Begin receiving upgraded preset
append@182: Succesfully received preset
receiveUpgradedPreset@1326: Replacing edit buffer for single program 64 with upgraded preset
sendSysex@691: Request Single, Bank 0, program 64
sendSysex@701: Request Multi, Bank 0, program 64
append@54: Begin reading sysex
append@133: End reading sysex
append@141: Received sysex: f000203301107140104df7
append@54: Begin reading sysex
append@133: End reading sysex
append@141: Received sysex: f000203301107140104df7
MIPS: 101.7450 (101.7450 avg), MHz: 226.4544 (226.4544 avg)
threadFunc@175: MIPS: 101.7450 (101.7450 avg), MHz: 226.4544 (226.4544 avg)
MIPS: 108.3125 (104.9354 avg), MHz: 240.9513 (233.4967 avg)
threadFunc@175: MIPS: 108.3125 (104.9354 avg), MHz: 240.9513 (233.4967 avg)
MIPS: 108.2847 (106.0308 avg), MHz: 240.8804 (235.9115 avg)
threadFunc@175: MIPS: 108.2847 (106.0308 avg), MHz: 240.8804 (235.9115 avg)
MIPS: 107.5044 (106.3959 avg), MHz: 239.1480 (236.7134 avg)
threadFunc@175: MIPS: 107.5044 (106.3959 avg), MHz: 239.1480 (236.7134 avg)
MIPS: 108.3002 (106.7718 avg), MHz: 240.9159 (237.5430 avg)
threadFunc@175: MIPS: 108.3002 (106.7718 avg), MHz: 240.9159 (237.5430 avg)
MIPS: 108.2902 (107.0222 avg), MHz: 240.8968 (238.0960 avg)
threadFunc@175: MIPS: 108.2902 (107.0222 avg), MHz: 240.8968 (238.0960 avg)
MIPS: 108.3260 (107.2067 avg), MHz: 240.9719 (238.5030 avg)
threadFunc@175: MIPS: 108.3260 (107.2067 avg), MHz: 240.9719 (238.5030 avg)
MIPS: 107.4989 (107.2431 avg), MHz: 239.1349 (238.5818 avg)
threadFunc@175: MIPS: 107.4989 (107.2431 avg), MHz: 239.1349 (238.5818 avg)
MIPS: 108.2960 (107.3592 avg), MHz: 240.9130 (238.8388 avg)
threadFunc@175: MIPS: 108.2960 (107.3592 avg), MHz: 240.9130 (238.8388 avg)
terminate called after throwing an instance of 'std::bad_weak_ptr'
  what():  bad_weak_ptr
Aborted (core dumped)
codesound@codesound:~/opt/REAPER$

**Comment by dsp56300** [comment]
fixed in 1.3.15
