### ISSUE TITLE
Crash when selecting "hide duplicates". Both by name and hash.

### ISSUE THREAD

**Issue by cdelacruzpinto** [dsp56300/gearmulator#207]
Operating env:

- OS X Sonoma 14.2
- M1 Pro
- Logic Pro X 11
- Version 1.3.14 / Ti2 selected

How I can consistently reproduce:

* Open an instance of Tirus in Logic Pro X 11 
* Open the categories list under the patch list section
* Right click, then select "hide duplicates by name" or "hide duplicates by hash"
* The plugin / Logic consistenly crashes

Further remarks:

* Thanks for this amazing plugin and all your amazing work in general, and I actually don't care that much if it crashes from time to time... just filed this bug in case you want to improve it :-)

**Comment by dsp56300** [comment]
fixed in 1.3.15
