### ISSUE TITLE
OSTIRUS

### ISSUE THREAD

**Issue by Pospik2705** [dsp56300/gearmulator#213]
Hi, while Iam using my push3  and pushing some pads, some pads seems to be automaticaly mapped to knobs and other possibilities.. So while im playling notes on pads and pushing and sliding meanwhile, other controls from synth are on/off and adds values ...

any idea how to switch it off ? or ?

**Comment by dsp56300** [comment]
You have MPE enabled, you need to turn it off or filter these midi messages. The reason is that the Virus listens to control change messages for parameter changes that are used by MPE nowadays
