### ISSUE TITLE
Osirus/Ostirus: high idle usage

### ISSUE THREAD

**Issue by borkfomb** [dsp56300/gearmulator#224]
Hello, the idle cpu usage for these emus is very high.

Osirus 1.3.14 CLAP
- Idle: 4.80%
- Active: 5.25% (default patch playing a chord)

Ostirus 1.3.15 CLAP
- Idle: 8.60%
- Active: 10.15% (default patch playing a chord)

In comparison, 
- TAL-J-8, 0.10%
- DIVA, 0.40%
- FB-7999, 0.25%
- SURGE XT, 0.30%
- PAINOTEQ, 0.35%
- SPIRE, 0.10%
- KONTAKT with a 70gb library, 2.40%

Latency is high too but I'm sure that's known.
REAPER 7.22 x64 Windows

**Comment by grawlinson** [comment]
None of the synths that you’ve listed are emulating a full blown DSP chip, though.

**Comment by borkfomb** [comment]
The entire u-he and fullbucket vst collection (over 50 plugins) uses less cpu in total than 1 instance of Ostirus, a straight clone of a 30 year old dsp, and the response is deflection? Ok, good luck

**Comment by dddux** [comment]
These true hardware emulations are working quite differently to all these VST synths you mentioned. These have to run chip emulations in the background and emulating Motorola 563xx chips cost a lot of CPU in comparison to a normal VSTi that doesn't need to run a DSP chip emu to run the native DSP code within the emulation.

**Comment by insolace** [comment]
Native code will always outperform emulation on different architecture, 24/31bit addressing.Completely different instruction sets.On Sep 9, 2024, at 7:06 AM, borkfomb ***@***.***> wrote:﻿
The entire u-he and fullbucket vst collection (over 50 plugins) uses less cpu in total than 1 instance of Ostirus, a straight clone of a 30 year old dsp, and the response is deflection? Ok, good luck

**Comment by dsp56300** [comment]
A Tetris written for Windows will use less CPU than emulating a Nintendo SNES running Tetris. That's the nature of emulation
