### ISSUE TITLE
Any chance for win32 release beside current win64?

### ISSUE THREAD

**Issue by michaelsjackson** [dsp56300/gearmulator#44]
Would be cool. Thanks for this great project.

**Comment by NeirexStudio** [comment]
Why? If you use such an old cpu you won’t be able to use emulator anyway. For me it’s a waste of time to develop for outdated platform

**Comment by dsp56300** [comment]
Unfortunately, a 32 bit version is not possible due to the DSP having registers with more than 32 bits. The overhead would be so costly that it would not run in realtime. I recommend to use bridging plugins such as JBridge to use the emulator in a 32 bit host.
