### ISSUE TITLE
NKS save only recalling the first preset.

### ISSUE THREAD

**Issue by gormanj** [dsp56300/gearmulator#46]
Recalling an NKS preset that was saved only loads the first preset regardless of which preset was active when the NKS preset was saved. In other words, the plugin does not seem to save the complete state of itself. I think this may referred to as "making all the parameters visible to the instrument/vst." I understand this isn't really an issue when using the plugin alone, but it probably presents itself in other situations like recalling a saved song from a DAW where you expect the same configuration/presets on your plugins to recalled.

I plan on making an NKS bank with sound previews available for the public at the NKS User Forums for the virus_cl_061_release.bin if this is able to be implemented.

**Comment by talaviram** [comment]
1. are you seeing different behavior with other __non__ nks plug-ins?
2. NKS is a closed source licensed VST extension.
