### ISSUE TITLE
Parameter crosstalk between filter and vocoder section!

### ISSUE THREAD

**Issue by jaffasplaffa** [dsp56300/gearmulator#47]
Hello :) 

First this is a really great project. Sold my Virus C some years ago, so this is very welcome. Thanks for the hard work and making this available.

Here are a few things I noticed when playing around with the plugin and Virus C emulation:

**Filter and vocoder crosstalk between parameters:**
- Filter balance affects source balance in the vocoder section.
- Filter envelope sustain time affects spectral balance in the vocoder section.
- Filter envelope release affects vocoder bands in the vocoder section.
- Filter envelope attack affects vocoder attack in the vocoder section.
- Filter envelope decay affects vocoder decay in the vocoder section.
- Cutoff 1 parameter affects center frequency in the vocoder section.
- Resonance 1 parameter affects q factor in the vocoder section.
- Keytrack 1 parameter affects spread in the vocoder section.

And vice versa, the crosstalk goes both ways.

Just thought I'd mention it.

Best wishes, 
Jakob

**Comment by dsp56300** [comment]
not a bug, this is the same behaviour on the hardware, there is no way to change this
