### ISSUE TITLE
Amp Env broken after using INPUT preset

### ISSUE THREAD

**Issue by valentino-sm** [dsp56300/gearmulator#57]
## Describe the issue
Amp envelope stops working. Release flops at ends of long notes

## To reproduce
1. Load the preset ">>INPUT<<".
2. Load any other preset and check Amp Attack/Release behavior.

Touching "Input Mode" in the settings returns the amp to its normal state.

## Configuration

- DSP563xx Emulator Virus Edition v1.2.5 AU
- MacBook Air M1
- macOS Monterey 12.0.1
(I had experienced the issue in Win as well)

**Comment by RogerLevy** [comment]
Confirmed

**Comment by mkruselj** [comment]
Cannot confirm with latest Osirus.
