### ISSUE TITLE
// comments in parameterDescriptions_C.json cause crashes on Mac

### ISSUE THREAD

**Issue by MulB** [dsp56300/gearmulator#66]
Thanks for the great work!

I compiled the sources, which went smoothly, but running
the app or loading the AU, VST, … in a DAW caused crashes.
I debugged on Mac with Xcode/lldb and found out that the crashes
occur inside the routine that loads

source/jucePlugin/parameterDescriptions_C.json

since there are C++ comments (// …) in the json file.
Removing all // comments (which I think are not allowed in json)
solves the problem and then everything works fine.

Thus, I suggest to remove the // comments from the json file.

**Comment by dsp56300** [comment]
Thanks for the report, this is apparently only happening on Mac, not on Windows.

Even though these comments look like C++, these are JSON 5 comments, see here: https://json5.org/

There is code in the repo to remove the comments, I assume the issue is caused by the line endings being different on Mac/Linux than on Windows. I'm gonna look into it.

**Comment by MulB** [comment]
I think I spotted the bug. Already when I debugged, I noted that instead of the first comment there was ",\n" left in the json string.
This looked as if removeComments doesn't remove the final 2 characters of the comment. In fact:
Line 29 of VirusParameterDescriptions.cpp,
				_json.erase(pos, end - pos - 1);
uses a wrong formula for the length of the comment (pos: 1st char, end: last char to be removed). Thus, it should be
				_json.erase(pos, end - pos + 1);

With this change it works on my Mac. Hope this helps.

**Comment by dsp56300** [comment]
indeed, this only worked on windows because there is \r\n and the error was not obvious. thanks!

**Comment by MulB** [comment]
Thanks. I think the || removeBlock("/*", "*/") part in the if

still won't work since then _json[end]='*' and the

current version will not remove the trailing / of */.

 
 

Gesendet: Mittwoch, 23. Februar 2022 um 22:49 Uhr
Von: "dsp56300" ***@***.***>
An: "dsp56300/gearmulator" ***@***.***>
Cc: "MulB" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [dsp56300/gearmulator] // comments in parameterDescriptions_C.json cause crashes on Mac (Issue #66)


 

indeed, this only worked on windows because there is \r\n and the error was not obvious. thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MulB** [comment]
Sorry, I meant: in the while loop (not in the if).
 

Gesendet: Mittwoch, 23. Februar 2022 um 23:11 Uhr
Von: "Michael Ulbrich" ***@***.***>
***@***.***
Betreff: Aw: Re: [dsp56300/gearmulator] // comments in parameterDescriptions_C.json cause crashes on Mac (Issue #66)



Thanks. I think the || removeBlock("/*", "*/") part in the if

still won't work since then _json[end]='*' and the

current version will not remove the trailing / of */.

 
 

Gesendet: Mittwoch, 23. Februar 2022 um 22:49 Uhr
Von: "dsp56300" ***@***.***>
An: "dsp56300/gearmulator" ***@***.***>
Cc: "MulB" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [dsp56300/gearmulator] // comments in parameterDescriptions_C.json cause crashes on Mac (Issue #66)


 

indeed, this only worked on windows because there is \r\n and the error was not obvious. thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dsp56300** [comment]
yeah stupid me today. The correct fix is
_json.erase(pos, end - pos + _end.size());
thanks!
