### ISSUE TITLE
potential VST3 packaging issues

### ISSUE THREAD

**Issue by nipsy** [dsp56300/gearmulator#71]
I spent some time getting all of this working under Linux with Reaper (also Ardour and Carla) and ran into what I think are some issues with the way the VST3 plugin is being packaged and distributed.  By simply installing the .deb package on my Debian testing system for the VST3 version of the Linux native plugin, none of my VST hosts were seeing the VST3 version of the plugin.  However, once I created a similar directory structure I've seen used in other VST3 plugins under Linux, I was able to successfully load the VST3 plugin, albeit with some additional weirdness, which I will clarify below.

The working layout I finally stumbled upon combined the installed Debian package with pieces in my home directory.  I imagine that creating a similar layout directly under `/usr/local/lib/vst3` would probably work as well.  Either way, simply specifying `/usr/local/lib/vst3` immediately after installing the VST3 package wasn't working without doing the rest of this.

I did the following:

```
mkdir -p ~/.vst3/DSP56300Emu.vst3/Contents/x86_64-linux
ln -s /usr/local/lib/vst3/DSP56300Emu.so ~/.vst3/DSP56300Emu.vst3/Contents/x86_64-linux
```

This got me a working plugin, but missing the ROM files.  The weirdness I mentioned earlier was that I finally discovered that I needed to put either of my available B or C .bin ROM files in `~/.vst3` directly for them to be discovered, rather than placing them anywhere under `~/.vst3/DSP56300Emu.vst3` or even `~/DSP56300 Emulator` as I might have expected.  Related to that, there was also no immediately obvious way to swap between the two through the user interface.  And since they only seem to load correctly when placed in `~/.vst3`, swapping between the two requires some manual intervention to move those files around in that directory, which seems less than ideal (and also seems to prevent the ability to load both at the same time potentially).

Past that, I also saw some rather heavy idle CPU usage from both the VST2 and VST3 versions.  I saw MIPS numbers being spit out at one point when trying to debug all of the above, so I'm guessing that's the actual emulated DSP being run which is eating up CPU even when "idle".  Not sure if this is something that can be improved or will always be an issue with the way this is being emulated.

Anyway, thought I'd at least report this here in case anyone else stumbles across any of this.  Maybe I'm just doing something entirely wrong.  If not, maybe some of this can be addressed moving forward.

Regardless, this sounds FANTASTIC!

**Comment by dromer** [comment]
Yes the VST3 installer doesn't contain a valid VST3-bundle and you indeed have to place the ROM in the current VST3 root.

**Comment by grawlinson** [comment]
Would it make sense to have the program search for a folder in the user's home directory? I know Linux has XDG_DATA_HOME (`$HOME/.local/share`), not sure about other OSes.

Or it may be easier to have the ability to open a specific ROM file with a FileDialog window or something.
