### ISSUE TITLE
When saving and loading a single preset, semitone is off-by-one

### ISSUE THREAD

**Issue by basdp** [dsp56300/gearmulator#75]
When saving a patch with the save button on top, and then loading the patch, the semitone of -1 for some of the osc (might be all). I suspect there might be more off-by-one issues with saving/loading patches.

I think it is in the saving stage, not loading.

Version: v1.2.10
Platform: MacOS and Windows (Linux not tested)
DAW: Bitwig
ROM: Virus C 6v6

**Comment by dsp56300** [comment]
dupe of #83

**Comment by basdp** [comment]
I'm note sure if this is a dupe per se, as I have this on OSC 1. Just for completeness :-)
