### ISSUE TITLE
LV2 plugin format

### ISSUE THREAD

**Issue by dromer** [dsp56300/gearmulator#8]
You could've expected this coming :)

LV2 is a liberally licensed open-source plugin format that is extensible to application specific features and there has seen an increase of cross-platform hosts that support it over the last years.
Could be quite useful for an emulator I'd say: https://lv2plug.in/pages/why-lv2.html

**Comment by dromer** [comment]
I know this would be quite a trajectory to take, given the dependency on ctrlr (already not very reliable base) and then (currently) needing a juce-fork to bring LV2 capabilities -> https://github.com/RomanKubiak/ctrlr/issues/333

However there are now a great number of opensource juce plugins providing lv2 builds, and I don't see why we can't put it on the roadmap over here as well :)

**Comment by dsp56300** [comment]
Don't worry about ctrlr, we don't need ctrlr and I'm going to create a Juce fork anyway as I had to do some Juce fixes already.

The issue is: https://github.com/juce-framework/JUCE/issues/123

**Comment by dromer** [comment]
This is why https://github.com/lv2-porting-project/JUCE exists.

Projects like ChowDSP and Surge are using this for (experimental) LV2 builds. Just putting a pin in it and we can track updates for the future.

Are your fixes published anywhere?

**Comment by dromer** [comment]
Jatin did a nice write-up here: https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3

**Comment by dromer** [comment]
Extremely preliminary work here: https://github.com/dsp56300/gearmulator/compare/dsp56300...Wasted-Audio:feature/lv2?expand=1

vst3 and lv2 load. virus b/c roms work,  but get xruns on both

**Comment by dromer** [comment]
JUCE7 has been released today! :)
