### ISSUE TITLE
<@369354776842076160>,<#841809045505703956>,Some minor ui bug - in the eq section double click on gain knob results 0 instead of 63,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/957741011092775012)

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#80]
<@369354776842076160>,<#841809045505703956>,Some minor ui bug - in the eq section double click on gain knob results 0 instead of 63,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/957741011092775012)

**Comment by ylmrx** [comment]
issue affecting also Q factors (and freq default on center is likely the behavior we want too)
