### ISSUE TITLE
GUI size not remembered / opened with wrong scale

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#90]
<@723033594351845399>,<#841809045505703956>,but as default it loaded like this 😄,[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/966338422056816682)

**Comment by ylmrx** [comment]
issue = the resizing doesn't work. this is on win10, and latest FL Studio version

I'm reproducing this issue with Renoise 3.4.1 (the VST windows (in those DAW) is resizable by default, but gearmulator is not)
