### ISSUE TITLE
<@228175224263147523>,<#841809045505703956>,* nitpick for the Hoverland skin - bipolar parameters don't have bipolar knobs (at 12 o clock there should be no fill, at minimum value the fill should go from the left to 12 o clock, at maximum value the fill should go from 12 o clock to the right)
* when hovering above a control and mousewheeling, parameter display doesn't update the value (only works on mouse drag),[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/966828814976049212)

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#91]
<@228175224263147523>,<#841809045505703956>,* nitpick for the Hoverland skin - bipolar parameters don't have bipolar knobs (at 12 o clock there should be no fill, at minimum value the fill should go from the left to 12 o clock, at maximum value the fill should go from 12 o clock to the right)
* when hovering above a control and mousewheeling, parameter display doesn't update the value (only works on mouse drag),[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/966828814976049212)

**Comment by ylmrx** [comment]
https://github.com/dsp56300/gearmulator/pull/92 :)
