### ISSUE TITLE
Plugin crash when exporting skin to disk

### ISSUE THREAD

**Issue by dsp56300** [dsp56300/gearmulator#93]
<@421416101507891210>,<#841809045505703956>,Is this issue reported already? (same behaviour in Cubase 12.0.20),[Jump To](https://discordapp.com/channels/829099347975208970/841809045505703956/971083142402306098)

**Comment by ylmrx** [comment]
dupes #83

**Comment by mkruselj** [comment]
I cannot confirm this over here.
